'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Partial Public Class Application
    #Region "Primitive Properties"

    Public Overridable Property ID As Integer

    Public Overridable Property FirstName As String

    Public Overridable Property LastName As String

    Public Overridable Property Email As String

    Public Overridable Property AccountNo As Integer

    Public Overridable Property LoanType As String

    Public Overridable Property Principle As Integer

    Public Overridable Property InterestRate As Decimal

    Public Overridable Property TotalInterest As Decimal

    Public Overridable Property TotalInstalments As Decimal

    Public Overridable Property [Date] As Date

    #End Region
End Class
