'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel.DataAnnotations
Partial Public Class contact
    #Region "Primitive Properties"
    Public Overridable Property ID As Integer
    <Required(ErrorMessage:="Name requried")>
    Public Overridable Property Name As String
    <Required(ErrorMessage:="Subject requried")>
    Public Overridable Property Subject As String
    <Required(ErrorMessage:="Email requried")>
    <DataType(DataType.EmailAddress)>
    <RegularExpression("^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
        ErrorMessage:="Provide valid email address")>
    Public Overridable Property Email As String
    <Required(ErrorMessage:="Comment requried")>
    Public Overridable Property Comment As String
    <Display(Name:="Time")>
    Public Overridable Property TimeSent As Date

    #End Region
End Class
