'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.EntityClient

Partial Public Class LemsDataEntities
    Inherits ObjectContext
    Public Const SettingsConnectionString As String = "name=LemsDataEntities"
    Public Const ContainerName As String = "LemsDataEntities"

#Region "Constructors"

    Public Sub New()
        MyBase.New(SettingsConnectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, ContainerName)
        MyBase.ContextOptions.LazyLoadingEnabled = True
    End Sub

#End Region
#Region "ObjectSet Properties"

    Public ReadOnly Property Profiles() As ObjectSet(Of Profile)
        Get
            If _profiles Is Nothing Then
                _profiles = CreateObjectSet(Of Profile)("Profiles")
            End If
            Return _profiles
        End Get
    End Property
    Private _profiles As ObjectSet(Of Profile)

    Public ReadOnly Property UserTables() As ObjectSet(Of UserTable)
        Get
            If _userTables Is Nothing Then
                _userTables = CreateObjectSet(Of UserTable)("UserTables")
            End If
            Return _userTables
        End Get
    End Property
    Private _userTables As ObjectSet(Of UserTable)

    Public ReadOnly Property Applications() As ObjectSet(Of Application)
        Get
            If _applications Is Nothing Then
                _applications = CreateObjectSet(Of Application)("Applications")
            End If
            Return _applications
        End Get
    End Property
    Private _applications As ObjectSet(Of Application)

    Public ReadOnly Property Status() As ObjectSet(Of Statu)
        Get
            If _status Is Nothing Then
                _status = CreateObjectSet(Of Statu)("Status")
            End If
            Return _status
        End Get
    End Property
    Private _status As ObjectSet(Of Statu)

    Public ReadOnly Property StateAudits() As ObjectSet(Of StateAudit)
        Get
            If _stateAudits Is Nothing Then
                _stateAudits = CreateObjectSet(Of StateAudit)("StateAudits")
            End If
            Return _stateAudits
        End Get
    End Property
    Private _stateAudits As ObjectSet(Of StateAudit)

    Public ReadOnly Property AdminDetailAudits() As ObjectSet(Of AdminDetailAudit)
        Get
            If _adminDetailAudits Is Nothing Then
                _adminDetailAudits = CreateObjectSet(Of AdminDetailAudit)("AdminDetailAudits")
            End If
            Return _adminDetailAudits
        End Get
    End Property
    Private _adminDetailAudits As ObjectSet(Of AdminDetailAudit)

    Public ReadOnly Property LostPasswords() As ObjectSet(Of LostPassword)
        Get
            If _lostPasswords Is Nothing Then
                _lostPasswords = CreateObjectSet(Of LostPassword)("LostPasswords")
            End If
            Return _lostPasswords
        End Get
    End Property
    Private _lostPasswords As ObjectSet(Of LostPassword)

    Public ReadOnly Property Tokens() As ObjectSet(Of Token)
        Get
            If _tokens Is Nothing Then
                _tokens = CreateObjectSet(Of Token)("Tokens")
            End If
            Return _tokens
        End Get
    End Property
    Private _tokens As ObjectSet(Of Token)

    Public ReadOnly Property Audits() As ObjectSet(Of Audit)
        Get
            If _audits Is Nothing Then
                _audits = CreateObjectSet(Of Audit)("Audits")
            End If
            Return _audits
        End Get
    End Property
    Private _audits As ObjectSet(Of Audit)

    Public ReadOnly Property Messages() As ObjectSet(Of Message)
        Get
            If _messages Is Nothing Then
                _messages = CreateObjectSet(Of Message)("Messages")
            End If
            Return _messages
        End Get
    End Property
    Private _messages As ObjectSet(Of Message)

    Public ReadOnly Property contacts() As ObjectSet(Of contact)
        Get
            If _contacts Is Nothing Then
                _contacts = CreateObjectSet(Of contact)("contacts")
            End If
            Return _contacts
        End Get
    End Property
    Private _contacts As ObjectSet(Of contact)

#End Region
End Class
