'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel.DataAnnotations
Partial Public Class Profile
    #Region "Primitive Properties"

    Public Overridable Property ID As Integer
    <Required(ErrorMessage:="Account Number requried")>
    <Display(Name:="Account Number")>
    Public Overridable Property AccountNo As Integer
    <Required(ErrorMessage:="First name requried")>
    <Display(Name:="First Name")>
    Public Overridable Property FirstName As String
    <Required(ErrorMessage:="Last name requried")>
    <Display(Name:="Last Name")>
    Public Overridable Property LastName As String
    <Display(Name:="Date Created")>
    Public Overridable Property DateCreated As Date
    <Required(ErrorMessage:="Share Deposits requried")>
    <Display(Name:="Share Deposits")>
    Public Overridable Property ShareDeposit As Integer

    #End Region
End Class
