'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized

Partial Public Class Statu
    #Region "Primitive Properties"

    Public Overridable Property ID As Integer

    Public Overridable Property AccountNo As Integer

    Public Overridable Property State As Integer

    Public Overridable Property Read As Integer

    #End Region
End Class
