'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports System.Collections
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel.DataAnnotations
Partial Public Class UserTable
    #Region "Primitive Properties"

    Public Overridable Property ID As Integer
    <Required(ErrorMessage:="Account Number requried")>
    <Display(Name:="Account Number")>
    Public Overridable Property AccountNo As Integer
    <Required(ErrorMessage:="Email requried")>
    <DataType(DataType.EmailAddress)>
    <RegularExpression("^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$",
        ErrorMessage:="Provide valid email address")>
    Public Overridable Property Email As String
    <DataType(DataType.Password)>
   <Required(ErrorMessage:="Enter password")>
    Public Overridable Property Password As String
    <Compare("Password", ErrorMessage:="Password don't match")>
   <DataType(DataType.Password)>
    <Display(Name:="Confirm Password")>
    Public Overridable Property ConfirmPassword As String

    #End Region
End Class
